include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    invalid_annotation_target: ignore
    no_leading_underscores_for_local_identifiers: ignore
    use_build_context_synchronously: ignore
