name: tyba_university_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  dio: ^5.8.0+1
  envied: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_gen: ^5.10.0
  freezed_annotation: ^2.4.1
  get_it: ^8.0.3
  go_router: ^15.1.1
  http: ^1.4.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.8
  envied_generator: ^1.1.1
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
